[2024-03-10 14:12:07,597][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=50, round_timeout=None)
[2024-03-10 14:12:14,511][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 28427241063.0, 'object_store_memory': 14213620531.0, 'node:127.0.0.1': 1.0, 'CPU': 24.0, 'node:__internal_head__': 1.0, 'GPU': 1.0}
[2024-03-10 14:12:14,512][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
[2024-03-10 14:12:14,512][flwr][INFO] - No `client_resources` specified. Using minimal resources for clients.
[2024-03-10 14:12:14,512][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
[2024-03-10 14:12:14,552][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 24 actors
[2024-03-10 14:12:14,553][flwr][INFO] - Initializing global parameters
[2024-03-10 14:12:14,554][flwr][INFO] - Requesting initial parameters from one random client
[2024-03-10 14:12:19,854][flwr][ERROR] - Traceback (most recent call last):
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
                                           ^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 98, in client_fn
    return FlowerClient(
           ^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 23, in __init__
    self.model = Net(num_classes)
                 ^^^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\model.py", line 92, in __init__
    self.densenet = models.densenet121(weights='IMAGENET1K_V2')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\densenet.py", line 368, in densenet121
    weights = DenseNet121_Weights.verify(weights)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_api.py", line 82, in verify
    obj = cls[obj.replace(cls.__name__ + ".", "")]
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\enum.py", line 790, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'IMAGENET1K_V2'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 72, in run\n    client = check_clientfn_returns_client(client_fn(cid))\n                                           ^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 98, in client_fn\n    return FlowerClient(\n           ^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 23, in __init__\n    self.model = Net(num_classes)\n                 ^^^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\model.py", line 92, in __init__\n    self.densenet = models.densenet121(weights=\'IMAGENET1K_V2\')\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 142, in wrapper\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 228, in inner_wrapper\n    return builder(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\densenet.py", line 368, in densenet121\n    weights = DenseNet121_Weights.verify(weights)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_api.py", line 82, in verify\n    obj = cls[obj.replace(cls.__name__ + ".", "")]\n          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\enum.py", line 790, in __getitem__\n    return cls._member_map_[name]\n           ~~~~~~~~~~~~~~~~^^^^^^\nKeyError: \'IMAGENET1K_V2\'\n',)

[2024-03-10 14:12:19,860][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
                                           ^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 98, in client_fn
    return FlowerClient(
           ^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 23, in __init__
    self.model = Net(num_classes)
                 ^^^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\model.py", line 92, in __init__
    self.densenet = models.densenet121(weights='IMAGENET1K_V2')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\densenet.py", line 368, in densenet121
    weights = DenseNet121_Weights.verify(weights)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_api.py", line 82, in verify
    obj = cls[obj.replace(cls.__name__ + ".", "")]
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\enum.py", line 790, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'IMAGENET1K_V2'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 72, in run\n    client = check_clientfn_returns_client(client_fn(cid))\n                                           ^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 98, in client_fn\n    return FlowerClient(\n           ^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 23, in __init__\n    self.model = Net(num_classes)\n                 ^^^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\model.py", line 92, in __init__\n    self.densenet = models.densenet121(weights=\'IMAGENET1K_V2\')\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 142, in wrapper\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 228, in inner_wrapper\n    return builder(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\densenet.py", line 368, in densenet121\n    weights = DenseNet121_Weights.verify(weights)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_api.py", line 82, in verify\n    obj = cls[obj.replace(cls.__name__ + ".", "")]\n          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\enum.py", line 790, in __getitem__\n    return cls._member_map_[name]\n           ~~~~~~~~~~~~~~~~^^^^^^\nKeyError: \'IMAGENET1K_V2\'\n',)
[2024-03-10 14:12:19,864][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
                                           ^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 98, in client_fn
    return FlowerClient(
           ^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 23, in __init__
    self.model = Net(num_classes)
                 ^^^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\model.py", line 92, in __init__
    self.densenet = models.densenet121(weights='IMAGENET1K_V2')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\densenet.py", line 368, in densenet121
    weights = DenseNet121_Weights.verify(weights)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_api.py", line 82, in verify
    obj = cls[obj.replace(cls.__name__ + ".", "")]
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\enum.py", line 790, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'IMAGENET1K_V2'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 72, in run\n    client = check_clientfn_returns_client(client_fn(cid))\n                                           ^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 98, in client_fn\n    return FlowerClient(\n           ^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 23, in __init__\n    self.model = Net(num_classes)\n                 ^^^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\model.py", line 92, in __init__\n    self.densenet = models.densenet121(weights=\'IMAGENET1K_V2\')\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 142, in wrapper\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 228, in inner_wrapper\n    return builder(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\densenet.py", line 368, in densenet121\n    weights = DenseNet121_Weights.verify(weights)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_api.py", line 82, in verify\n    obj = cls[obj.replace(cls.__name__ + ".", "")]\n          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\enum.py", line 790, in __getitem__\n    return cls._member_map_[name]\n           ~~~~~~~~~~~~~~~~^^^^^^\nKeyError: \'IMAGENET1K_V2\'\n',)
[2024-03-10 14:12:19,875][flwr][ERROR] - Traceback (most recent call last):
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\app.py", line 308, in start_simulation
    hist = run_fl(
           ^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\server\app.py", line 225, in run_fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\server\server.py", line 90, in fit
    self.parameters = self._get_initial_parameters(timeout=timeout)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\server\server.py", line 279, in _get_initial_parameters
    get_parameters_res = random_client.get_parameters(ins=ins, timeout=timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 196, in get_parameters
    res = self._submit_job(get_parameters, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 163, in _submit_job
    raise ex
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 151, in _submit_job
    res, updated_context = self.actor_pool.get_client_result(self.cid, timeout)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 425, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 306, in _fetch_future_result
    res_cid, res, updated_context = ray.get(
                                    ^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
                                           ^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 98, in client_fn
    return FlowerClient(
           ^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\client.py", line 23, in __init__
    self.model = Net(num_classes)
                 ^^^^^^^^^^^^^^^^
  File "J:\Rehaan's College Project\fed_tutorial_next\model.py", line 92, in __init__
    self.densenet = models.densenet121(weights='IMAGENET1K_V2')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\densenet.py", line 368, in densenet121
    weights = DenseNet121_Weights.verify(weights)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\torchvision\models\_api.py", line 82, in verify
    obj = cls[obj.replace(cls.__name__ + ".", "")]
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\enum.py", line 790, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'IMAGENET1K_V2'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=39176, ip=127.0.0.1, actor_id=251f0988099c61bdc995d4a901000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x000001C381984250>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Guddu\anaconda3\envs\rehaan\Lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 90, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client run.\n\tClient 6 crashed when the DefaultActor was running its run.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\flwr\\simulation\\ray_transport\\ray_actor.py", line 72, in run\n    client = check_clientfn_returns_client(client_fn(cid))\n                                           ^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 98, in client_fn\n    return FlowerClient(\n           ^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\client.py", line 23, in __init__\n    self.model = Net(num_classes)\n                 ^^^^^^^^^^^^^^^^\n  File "J:\\Rehaan\'s College Project\\fed_tutorial_next\\model.py", line 92, in __init__\n    self.densenet = models.densenet121(weights=\'IMAGENET1K_V2\')\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 142, in wrapper\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_utils.py", line 228, in inner_wrapper\n    return builder(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\densenet.py", line 368, in densenet121\n    weights = DenseNet121_Weights.verify(weights)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\site-packages\\torchvision\\models\\_api.py", line 82, in verify\n    obj = cls[obj.replace(cls.__name__ + ".", "")]\n          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "c:\\Users\\Guddu\\anaconda3\\envs\\rehaan\\Lib\\enum.py", line 790, in __getitem__\n    return cls._member_map_[name]\n           ~~~~~~~~~~~~~~~~^^^^^^\nKeyError: \'IMAGENET1K_V2\'\n',)

[2024-03-10 14:12:19,884][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 1, 'num_gpus': 0.0} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 1, 'num_gpus': 0.0}.
Take a look at the Flower simulation examples for guidance <https://flower.dev/docs/framework/how-to-run-simulations.html>.
